In [1]:
import datetime

import pandas as pd
import spacy
import re
import string
import numpy as np
import sys

import seaborn as sns
from matplotlib import cm
from matplotlib.pyplot import figure
import matplotlib.pyplot as plt
%matplotlib inline

from spacy.tokens import Token
from tqdm import tqdm
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

import nltk
from nltk.corpus import stopwords

from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

from sklearn.cluster import MiniBatchKMeans
from sklearn.cluster import DBSCAN
from sklearn.ensemble import IsolationForest
from sklearn.cluster import KMeans

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import silhouette_score
from sklearn import metrics

from sklearn.model_selection import ShuffleSplit

import gensim
from gensim import corpora, models
from gensim.models.phrases import Phrases, Phraser
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from gensim.models.coherencemodel import CoherenceModel
from gensim.models import Word2Vec
from gensim.models.doc2vec import Doc2Vec
import multiprocessing

from sklearn.model_selection import cross_val_score , GridSearchCV,train_test_split

from sklearn.naive_bayes import MultinomialNB,GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm

import enchant
pd.set_option('display.max_rows', 500)

In [45]:
dict_check = enchant.Dict("en_US")

#### Importing the file ####
Path="src/"

Filename='projects_Preprocessed.csv'
df=pd.read_csv(Path+Filename)

DBFilename='Report_WEPCADBScanFindingsKMeansV3_Exp1.csv'
DB_df=pd.read_csv(Path+DBFilename)

ISOForestFilename='Report_WEPCAISOForestFindingsKMeansV3.csv'
ISO_df=pd.read_csv(Path+ISOForestFilename)

manualtag=pd.read_csv(Path+'SamplesManualTagger.csv')

df['SubUrl']='https://gepris.dfg.de'+df['SubUrl']

## if it is interdiscipilinary then -1 otherwise 0 (Normal data)
manualtag['interdiscipilinary']=-1
manualtag.loc[manualtag.apply(lambda x: (x['Category']==x['Category_1']) & (pd.isnull(x['Category_2'])) , axis=1),'interdiscipilinary']=1

In [5]:
DB_df.interdiscipilinary.value_counts()

False    49410
True      1623
Name: interdiscipilinary, dtype: int64

In [6]:
ISO_df.interdiscipilinary.value_counts()

False    49529
True      1504
Name: interdiscipilinary, dtype: int64

In [48]:
Merged_df=ISO_df[['ProjectURL','Category','Category_1_Values', 'Category_2_Values','Category_1', 'Category_2','ISOForestCluster','interdiscipilinary'] ].merge(DB_df[['ProjectURL','Category_1_Values', 'Category_2_Values', 'Category_1', 'Category_2','DBScanCluster','interdiscipilinary' ]], how='inner', left_on='ProjectURL', right_on='ProjectURL',suffixes= ('_ISO','_DB'))
Merged_df=Merged_df.merge(df[['SubUrl','Translates']],how='left',left_on='ProjectURL',right_on='SubUrl')
Feature=['Translates','Category','Category_1_DB','Category_1_ISO','Category_2_DB','Category_2_ISO']

In [49]:
Merged_df.columns

Index(['ProjectURL', 'Category', 'Category_1_Values_ISO',
       'Category_2_Values_ISO', 'Category_1_ISO', 'Category_2_ISO',
       'ISOForestCluster', 'interdiscipilinary_ISO', 'Category_1_Values_DB',
       'Category_2_Values_DB', 'Category_1_DB', 'Category_2_DB',
       'DBScanCluster', 'interdiscipilinary_DB', 'SubUrl', 'Translates'],
      dtype='object')

In [50]:
Merged_df.groupby(['interdiscipilinary_DB','interdiscipilinary_ISO']).count()[['ProjectURL']]

ProjectURL
interdiscipilinary_DB interdiscipilinary_ISO            
False                 False                        48481
                      True                           935
True                  False                         1048
                      True                           569

In [51]:
Merged_df[((Merged_df.interdiscipilinary_DB) & (Merged_df.interdiscipilinary_ISO==False ) )][Feature+['ISOForestCluster']].head(100)

Translates  \
217   The application area ZE Education covers the a...   
449   The aim of this project is to develop efficien...   
531   Uncertainty occurs during the development of p...   
532   Statistical modeling is the methodology of con...   
767   The research program is rooted in geometry. Th...   
790   Contents Nowadays, modern technologies in life...   
918   Vector optimization is a continuously growing ...   
952   The ability to invade tissue and form metastas...   
988   Biomedical imaging aims at visualizing structu...   
1017  In this project we want to analyze finite elem...   
1049  With greatly advanced computational resources,...   
1052  The International Research Training Group (IRT...   
1216  The software Ubiquity Generator is a uniquely ...   
1254  In this project we want to investigate drawing...   
1267  Modern applications of control theory to chemi...   
2152  The device is to be procured for the research ...   
2193  Ultrashort pulse lasers with high pulse energi...   
2241  The Rearch Training Group IGRA puts its focus ...   
2305  The aim is to develop a Conchostraken zone cla...   
2370  This research project, in collaboration with t...   
2622  The geosciences are currently developing into ...   
2751  Specialized herbivores are found in a wide var...   
2837  The pelvis is of great functional importance i...   
2875  Interactions among species are one of the most...   
2900  In 2009, Expedition 323 of the Integrated Ocea...   
2915  Turtles are unique among vertebrates in that t...   
2956  Approximately 90% of the seismic moment on Ear...   
2973  Here, we propose a web-based, open-access, dig...   
3001  Funds are requested for mineralogical and geoc...   
3011  Despite the great diversity and particular eco...   
3050  Ornithopod dinosaurs are one of the most succe...   
3063  This proposal was inspired by the inherent lim...   
3072  Theropod dinosaurs represent one of the most c...   
3083  The plesiomorphic molariform pattern of stem-m...   
3127  The relevance of physiology in studies of clim...   
3177  Mesosaurs are a unique and very specialized ve...   
3179  Understanding the interplay between brittle an...   
3191  The worlds largest and likely most famous ammo...   
3206  It has long been recognized that in addition t...   
3207  Silicification is the most important fossiliza...   
3226  The family of Dicraeosauridae (Jurassic-Cretac...   
3252  The skulls of land vertebrates are characteriz...   
3255  Representatives of Crocodylia, the group inclu...   
3264  The Island of Crete is situated in a fore-arc ...   
3267  The rich information on past extinctions provi...   
3273  The Iberian Peninsula is one of the southern r...   
3291  "The Chair of Inorganic-Non-Metallic Materials...   
3300  The SALVE (Sub Ånström Low Voltage Electron Mi...   
3311  Information processing is currently dominated ...   
3336  The treatment of patients with chronic brain d...   
3345  The proposed RTG aims to improve understanding...   
3441  The research projects consist mainly of atomic...   
4038  In this research proposal, genes belonging to ...   
4043  Atlases are an integral part of scientific lib...   
4070  Modern software has to cope with ever-changing...   
4072  Mobile information and communication technolog...   
4085  Various chemistry courses at the RWTH Aachen f...   
4280  The Karlsruhe School of Elementary Particle an...   
4311  "The Sport Science working group" Neuromechani...   
4312  "The devices mentioned here serve to set up a ...   
4314  The proposed motion analysis system (BAS), con...   
4432  Growing food prices and high liquidity in inte...   
4456  The characterization and distinction of wines ...   
4485  The aim of the research project is the develop...   
4504  Nuclear Magnetic Resonance (NMR) is a non-inva...   
4553  In the proposed work, we plan to develop novel...   
4618  Metals and metalloproteins play a key-role in ...   
4623  Metals and metalloproteins 

In [52]:
Merged_df[((Merged_df.interdiscipilinary_DB) & (Merged_df.interdiscipilinary_ISO==False ) )]['Translates'].head(100).tolist()

['The application area ZE Education covers the areas of competence training, further education and course development. Our educational competence is based on the experience of teaching students with the subject of mathematics for all types of schools (elementary school, secondary school, high school) and with students of engineering. Wide acclaim has been found in our successful efforts to strengthen the practice orientation of teacher training. In addition, the competence in this field is based on our great successes in the promotion of mathematically gifted and interested students in the "Berlin network of mathematically-scientifically-profiled schools". Continuing education is demonstrated through our innovative approach to teacher education. Its increased national impact is confirmed by the project "Mathematics Anders Machen" funded by the Deutsche Telekom Foundation. Our course development expertise brings together our extensive experience in the development of teaching materials 

In [53]:
Merged_df[((Merged_df.interdiscipilinary_DB) & (Merged_df.interdiscipilinary_ISO ) )][Feature]

Translates  \
107    In this project, the calcium-regulated force d...   
543    The transregional CRC 73 was initiated to esta...   
559    The aim of this interdisciplinary project is t...   
595    Herein, we describe recent results and future ...   
914    The latest and still ongoing discussion on Die...   
1060   The sequentially Markov coalescent (SMC) is an...   
1062   The CRISPR-Cas system (Clustered Regularly Int...   
1298   Our project aims to investigate the influence ...   
1847   Historical buildings are components of cultura...   
2156   Quantitative economics often faces the challen...   
2714   To understand the two-way interaction between ...   
2779   Although Cedrela (Meliaceae) is one of the wor...   
2780   The origins and relationships of the Otariidae...   
2873   Computer Aided Engineering (CAE) is increasing...   
2881   Pictures of theropods preying on large sauropo...   
2932   Cynodontia within mammal-like reptiles play a ...   
2979   Climate and environmental changes, as well as ...   
2988   South America was isolated during most of the ...   
3008   The insect-biostratigraphy has proven as one o...   
3020   Species-building and extinction are the two ma...   
3133   Paleopathology is the study of illness and inj...   
3145   Biomineralization is the biological controlled...   
3161   The clade of Archosauria consists of two main ...   
3180   Salamanders are extraordinary among tetrapods ...   
3188   Starting with a terrestrial ancestral state, m...   
3205   Fossil evidence indicates that plants and inse...   
3211   During an impact event, the deformation of min...   
3257   The vertebrate mineralized skeleton is among t...   
3261   The EarthShape priority program defines four t...   
3356   Quantitative element analysis plays a central ...   
3790   The research unit FOR 1847 asks for a second p...   
3995   Herewith, we are applying for the financial fu...   
4319   The new biochemical wet laboratory to be set u...   
4320   Mass-spectrometry (MS) based quantitative prot...   
4518   With industrialization at the end of the 19th ...   
4546   The currently available diagnostic methods in ...   
4619   Raman microspectroscopy on cells and tissues a...   
4645   Point-of-care diagnostics for personalized med...   
4666   Analyzing the spatial distribution of proteins...   
4696   RNA and its modifications are dynamically regu...   
4701   Bacteria rarely occur in their planktonic form...   
4752   The conflicts between resident farmers and nom...   
4766   Business start-ups contribute to economic stru...   
4768   This volume is divided into two parts. The fir...   
5147   As has been known for several years, femtoseco...   
5154   Scientific associations have a very special re...   
5198   Byssal threads are biopolymeric fibers secrete...   
5318   Interfacial transport phenomena of heat, mass ...   
5357   Volatile organic compounds (VOCs) play an impo...   
5359   The herein requested mass spectrometer shall b...   
5911   The RTG focuses on the Conducive Design of the...   
8160   The aim of the project is to assess regional s...   
8316   Despite consensus on South America as being th...   
8940   This line of research develops theory and meth...   
9030   Understanding the mechanism of molecular hydro...   
9060   Self-organized metachronal waves in cilia carp...   
9089   Iron-sulfur clusters play central role in many...   
9116   Multivalent interactions are observed in a mul...   
9544   Cyanobacterial cyclic and linear peptide secon...   
9640   Underground de-ironing and demanganization (UE...   
9646   Parasites are creatures that live at the expen...   
9696   Copepods play a crucial role in the food webs ...   
9740   Recent studies on seasonal dynamics of phytopl...   
9777   Understanding trophic interactions and food we...   
9799   Human waterborne pathogens such as bacteria, p...   
9862   Drought events pose a threat to water security...   
9863   The expansion of in

In [54]:
len(Merged_df[((Merged_df.interdiscipilinary_DB) & (Merged_df.interdiscipilinary_ISO ) )][Feature])

569

In [55]:
Merged_df.columns

Index(['ProjectURL', 'Category', 'Category_1_Values_ISO',
       'Category_2_Values_ISO', 'Category_1_ISO', 'Category_2_ISO',
       'ISOForestCluster', 'interdiscipilinary_ISO', 'Category_1_Values_DB',
       'Category_2_Values_DB', 'Category_1_DB', 'Category_2_DB',
       'DBScanCluster', 'interdiscipilinary_DB', 'SubUrl', 'Translates'],
      dtype='object')

In [56]:
ManualTaggedMerged=manualtag[['Translates', 'Category_1', 'Category_2','interdiscipilinary']].merge(Merged_df,how='left', left_on='Translates', right_on='Translates')

In [57]:
def combine_results(x):
    Actual=x['Category_1']
    cat1=x['Category']
    cat2=np.NaN
    
    if(x['interdiscipilinary_ISO'] and x['interdiscipilinary_DB'] ):
        
    ## Combining both results
               
        if(x['Category_1_DB'] == x['Category_1_ISO']):
            cat1= x['Category_1_DB']
            if(x['Category_2_ISO'] == x['Category_2_DB']):
                cat2= x['Category_2_DB']                
        elif(x['Category_1_DB'] == x['Category_2_ISO']):
            cat1= x['Category_1_DB']
            if(x['Category_2_DB'] == x['Category_1_ISO']):
                cat2= x['Category_2_DB']        
        elif(x['Category_2_DB'] == x['Category_1_ISO']):
            cat1= x['Category_2_DB']        
        else :
            cat1= x['Category']
            
    return pd.Series({'cat1':cat1,'cat2':cat2})
        
ManualTaggedMerged[['Category_1_combined','Category_2_combined']] =ManualTaggedMerged.apply(combine_results, axis=1)

In [58]:

## Function to take a better results for valudation
def rebuilt_ip(x):
    final_pred=x['Category_1_combined']
    final_actual=x['Category_1']
    result=0
    
    if(x['Category_1_combined'] == x['Category_1']):
        final_pred=x['Category_1_combined']
        final_actual=x['Category_1']
        result=1
        
    elif(x['Category_1_combined'] == x['Category_2']):
        final_pred=x['Category_1_combined']
        final_actual=x['Category_2']
        result=1
    
    elif(x['Category_2_combined'] == x['Category_1']):
        final_pred=x['Category_2_combined']
        final_actual=x['Category_1']
        result=.66
        
    elif(x['Category_2_combined'] == x['Category_2']):
        final_pred=x['Category_2_combined']
        final_actual=x['Category_2']
        result=.66

    return pd.Series({'pred':final_pred,'actual':final_actual,'result':result})


ManualTaggedMerged[['Predicted','Actual','Result']]=ManualTaggedMerged.apply(rebuilt_ip, axis=1)

In [59]:
# Print the confusion matrix
print(metrics.confusion_matrix(ManualTaggedMerged.Actual, ManualTaggedMerged.Predicted))

# Print the precision and recall, among other metrics
print(metrics.classification_report(ManualTaggedMerged.Actual, ManualTaggedMerged.Predicted, digits=3))

[[12  0  0  1]
 [ 1 11  0  0]
 [ 1  3 11  2]
 [ 0  0  0  8]]
                                precision    recall  f1-score   support

          Engineering Sciences      0.857     0.923     0.889        13
Humanities and Social Sciences      0.786     0.917     0.846        12
                 Life Sciences      1.000     0.647     0.786        17
              Natural Sciences      0.727     1.000     0.842         8

                      accuracy                          0.840        50
                     macro avg      0.843     0.872     0.841        50
                  weighted avg      0.868     0.840     0.836        50



## Used to generate the manual tagging records 

ID= ((Merged_df.interdiscipilinary_DB) & (Merged_df.interdiscipilinary_ISO ) )
Not_ID= ((Merged_df.interdiscipilinary_DB==False) & (Merged_df.interdiscipilinary_ISO==False) )
False_positivies= (Merged_df.DBScanCluster!=-1) & (Merged_df.ISOForestCluster!=-1) & (Merged_df.Category!=Merged_df.Category_1_DB) & (Merged_df.Category!=Merged_df.Category_1_ISO)

Samples=pd.DataFrame()

for cat in Merged_df.Category.unique():
    cat_filter=(Merged_df.Category==cat)
    
    Samples=pd.concat([Samples,Merged_df[(cat_filter) & (ID)].sample(n=24)], ignore_index=True)
    Samples=pd.concat([Samples,Merged_df[(cat_filter) & (Not_ID)].sample(n=24)], ignore_index=True)
    Samples=pd.concat([Samples,Merged_df[(cat_filter) & (False_positivies)].sample(n=8)], ignore_index=True)

Final_sample=Samples.sample(50)
Final_sample.Category.value_counts()
Final_sample.interdiscipilinary_ISO.value_counts()
#Final_sample[[ 'Category','Translates']].to_csv(Path+'SamplesManualTagger.csv', index=False)